### ISSUE TITLE
老哥，pandora项目没了，您那里还有源码吗，可以发我一份吗

### ISSUE THREAD

**Issue by luxx-lq** [xueandyue/vue3.0-demo#1]
您 [ChatGPT-AccessToken-Web] 项目没有issues，我就跑这里来了 ，想跟您要份pandora的源码

**Comment by xueandyue** [comment]
https://github.com/pandora-next/deploy

**Comment by luxx-lq** [comment]
老哥，docker版本可以支持4.0吗

**Comment by xueandyue** [comment]
最近没空，不打算弄了
